int     ft_atoi(char *str);
int     ft_atoi_base(char *str, char *base);
void    ft_print_words_tables(char **tab);
void    ft_putchar(char c);
void    ft_putnbr(int nb);
void    ft_putnbr_base(int nbr, char *base);
void    ft_putstr(char *str);
int     ft_recursive_power(int nb, int power);
void    ft_sort_integer_table(int *tab, int size);
char    **ft_split_whitespaces(char *str);
int     ft_str_is_alpha(char *str);
int     ft_str_is_lowercase(char *str);
int     ft_str_is_numeric(char *str);
char    *ft_strcapitalize(char *str);
char    *ft_strcat(char *dest, char *src);
int     ft_strcmp(char *s1, char *s2);
char    *ft_strcpy(char *dest, char *src);
char    *ft_strdup(char *src);
int     ft_strlen(char *str);
char    *ft_strlowcase(char *str);
char    *ft_strncat(char *dest, char *src, int nb);
int     ft_strncmp(char *s1, char *s2, unsigned int n);
char    *ft_strncpy(char *dest, char *src, unsigned int n);
char    *ft_strrev(char *str);
char    *ft_strstr(char *str, char *to_find);
char    *ft_strupcase(char *str);
void    ft_swap(int *a, int *b);
char    **ft_split(char *str, char *charset);
